export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LIST ="USER_LIST";
export const GET_MESSAGES ="GET_MESSAGES";
export const SET_TYPING_VALUE ="SET_TYPING_VALUE";
export const SEND_MESSAGE ="SEND_MESSAGE";
export const OPEN_CHAT_USER ="OPEN_CHAT_USER";
